# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Backup\coding\git\PyQT\PyQT_Chroma_Eload\PyQt_Chroma_Eload_GUI.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(727, 563)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.commandLinkButton = QtWidgets.QCommandLinkButton(self.centralwidget)
        self.commandLinkButton.setEnabled(True)
        self.commandLinkButton.setGeometry(QtCore.QRect(440, 480, 251, 41))
        self.commandLinkButton.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.commandLinkButton.setObjectName("commandLinkButton")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(280, 360, 411, 61))
        self.textBrowser.setObjectName("textBrowser")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(30, 450, 111, 71))
        self.pushButton_3.setObjectName("pushButton_3")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(30, 140, 661, 141))
        self.groupBox.setObjectName("groupBox")
        self.layoutWidget = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 20, 631, 105))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 0, 1, 1)
        self.comboBox = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBox.setEnabled(True)
        self.comboBox.setEditable(False)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.gridLayout.addWidget(self.comboBox, 4, 1, 1, 5)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 4, 0, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.layoutWidget)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 0, 3, 1, 1)
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.layoutWidget)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 0, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.lineEdit_L3 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_L3.setEnabled(False)
        self.lineEdit_L3.setObjectName("lineEdit_L3")
        self.gridLayout.addWidget(self.lineEdit_L3, 1, 2, 1, 1)
        self.lineEdit_L1 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_L1.setEnabled(False)
        self.lineEdit_L1.setObjectName("lineEdit_L1")
        self.gridLayout.addWidget(self.lineEdit_L1, 1, 1, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.layoutWidget)
        self.label_14.setObjectName("label_14")
        self.gridLayout.addWidget(self.label_14, 0, 5, 1, 1)
        self.lineEdit_L5 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_L5.setEnabled(False)
        self.lineEdit_L5.setObjectName("lineEdit_L5")
        self.gridLayout.addWidget(self.lineEdit_L5, 1, 3, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.layoutWidget)
        self.label_13.setObjectName("label_13")
        self.gridLayout.addWidget(self.label_13, 0, 4, 1, 1)
        self.lineEdit_L7 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_L7.setEnabled(False)
        self.lineEdit_L7.setObjectName("lineEdit_L7")
        self.gridLayout.addWidget(self.lineEdit_L7, 1, 4, 1, 1)
        self.lineEdit_L9 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_L9.setEnabled(False)
        self.lineEdit_L9.setObjectName("lineEdit_L9")
        self.gridLayout.addWidget(self.lineEdit_L9, 1, 5, 1, 1)
        self.checkBox_3 = QtWidgets.QCheckBox(self.layoutWidget)
        self.checkBox_3.setText("")
        self.checkBox_3.setChecked(False)
        self.checkBox_3.setObjectName("checkBox_3")
        self.gridLayout.addWidget(self.checkBox_3, 2, 2, 1, 1)
        self.checkBox_5 = QtWidgets.QCheckBox(self.layoutWidget)
        self.checkBox_5.setText("")
        self.checkBox_5.setObjectName("checkBox_5")
        self.gridLayout.addWidget(self.checkBox_5, 2, 3, 1, 1)
        self.checkBox_9 = QtWidgets.QCheckBox(self.layoutWidget)
        self.checkBox_9.setText("")
        self.checkBox_9.setObjectName("checkBox_9")
        self.gridLayout.addWidget(self.checkBox_9, 2, 5, 1, 1)
        self.checkBox_7 = QtWidgets.QCheckBox(self.layoutWidget)
        self.checkBox_7.setText("")
        self.checkBox_7.setObjectName("checkBox_7")
        self.gridLayout.addWidget(self.checkBox_7, 2, 4, 1, 1)
        self.checkBox_1 = QtWidgets.QCheckBox(self.layoutWidget)
        self.checkBox_1.setEnabled(True)
        self.checkBox_1.setText("")
        self.checkBox_1.setChecked(False)
        self.checkBox_1.setObjectName("checkBox_1")
        self.gridLayout.addWidget(self.checkBox_1, 2, 1, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(30, 300, 221, 121))
        self.groupBox_2.setObjectName("groupBox_2")
        self.layoutWidget1 = QtWidgets.QWidget(self.groupBox_2)
        self.layoutWidget1.setGeometry(QtCore.QRect(11, 17, 198, 91))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.layoutWidget1)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_16 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_16.setObjectName("label_16")
        self.gridLayout_5.addWidget(self.label_16, 0, 0, 1, 1)
        self.lineEdit_L51 = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEdit_L51.setEnabled(False)
        self.lineEdit_L51.setObjectName("lineEdit_L51")
        self.gridLayout_5.addWidget(self.lineEdit_L51, 0, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_9.setObjectName("label_9")
        self.gridLayout_5.addWidget(self.label_9, 1, 0, 1, 1)
        self.checkBox_51 = QtWidgets.QCheckBox(self.layoutWidget1)
        self.checkBox_51.setText("")
        self.checkBox_51.setObjectName("checkBox_51")
        self.gridLayout_5.addWidget(self.checkBox_51, 1, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_10.setObjectName("label_10")
        self.gridLayout_5.addWidget(self.label_10, 2, 0, 1, 1)
        self.comboBox_2 = QtWidgets.QComboBox(self.layoutWidget1)
        self.comboBox_2.setEnabled(True)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.gridLayout_5.addWidget(self.comboBox_2, 2, 1, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(380, 20, 311, 111))
        self.groupBox_3.setObjectName("groupBox_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_4.setEnabled(True)
        self.pushButton_4.setGeometry(QtCore.QRect(190, 20, 111, 31))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_5.setEnabled(True)
        self.pushButton_5.setGeometry(QtCore.QRect(190, 60, 111, 41))
        self.pushButton_5.setObjectName("pushButton_5")
        self.layoutWidget2 = QtWidgets.QWidget(self.groupBox_3)
        self.layoutWidget2.setGeometry(QtCore.QRect(7, 19, 171, 81))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.layoutWidget2)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_17 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_17.setObjectName("label_17")
        self.gridLayout_3.addWidget(self.label_17, 0, 0, 1, 1)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.layoutWidget2)
        self.lineEdit_5.setEnabled(True)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.gridLayout_3.addWidget(self.lineEdit_5, 0, 1, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_18.setObjectName("label_18")
        self.gridLayout_3.addWidget(self.label_18, 1, 0, 1, 1)
        self.lineEdit_6 = QtWidgets.QLineEdit(self.layoutWidget2)
        self.lineEdit_6.setEnabled(True)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.gridLayout_3.addWidget(self.lineEdit_6, 1, 1, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_20.setObjectName("label_20")
        self.gridLayout_3.addWidget(self.label_20, 2, 0, 1, 1)
        self.comboBox_3 = QtWidgets.QComboBox(self.layoutWidget2)
        self.comboBox_3.setEnabled(True)
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.gridLayout_3.addWidget(self.comboBox_3, 2, 1, 1, 1)
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_4.setGeometry(QtCore.QRect(30, 20, 331, 111))
        self.groupBox_4.setObjectName("groupBox_4")
        self.layoutWidget3 = QtWidgets.QWidget(self.groupBox_4)
        self.layoutWidget3.setGeometry(QtCore.QRect(17, 20, 171, 81))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.layoutWidget3)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_6 = QtWidgets.QLabel(self.layoutWidget3)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 0, 0, 1, 1)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.layoutWidget3)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout_2.addWidget(self.lineEdit_2, 0, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.layoutWidget3)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 1, 0, 1, 1)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.layoutWidget3)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.gridLayout_2.addWidget(self.lineEdit_3, 1, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.layoutWidget3)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 2, 0, 1, 1)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.layoutWidget3)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.gridLayout_2.addWidget(self.lineEdit_4, 2, 1, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton.setGeometry(QtCore.QRect(200, 20, 111, 81))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setEnabled(True)
        self.pushButton_2.setGeometry(QtCore.QRect(160, 450, 111, 71))
        self.pushButton_2.setObjectName("pushButton_2")
        self.groupBox_5 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_5.setGeometry(QtCore.QRect(290, 450, 141, 71))
        self.groupBox_5.setObjectName("groupBox_5")
        self.checkBox = QtWidgets.QCheckBox(self.groupBox_5)
        self.checkBox.setGeometry(QtCore.QRect(20, 30, 91, 17))
        self.checkBox.setChecked(True)
        self.checkBox.setObjectName("checkBox")
        self.layoutWidget4 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget4.setGeometry(QtCore.QRect(280, 310, 411, 41))
        self.layoutWidget4.setObjectName("layoutWidget4")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.layoutWidget4)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_19 = QtWidgets.QLabel(self.layoutWidget4)
        self.label_19.setObjectName("label_19")
        self.gridLayout_4.addWidget(self.label_19, 0, 0, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.layoutWidget4)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout_4.addWidget(self.lineEdit, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 727, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.commandLinkButton.setText(_translate("MainWindow", "Start to measure efficiency"))
        self.pushButton_3.setText(_translate("MainWindow", "test2"))
        self.groupBox.setTitle(_translate("MainWindow", "Eload1 Chroma 63640*5"))
        self.label_4.setText(_translate("MainWindow", "Select "))
        self.comboBox.setCurrentText(_translate("MainWindow", "1"))
        self.comboBox.setItemText(0, _translate("MainWindow", "1"))
        self.comboBox.setItemText(1, _translate("MainWindow", "2"))
        self.comboBox.setItemText(2, _translate("MainWindow", "3"))
        self.comboBox.setItemText(3, _translate("MainWindow", "4"))
        self.comboBox.setItemText(4, _translate("MainWindow", "5"))
        self.comboBox.setItemText(5, _translate("MainWindow", "6"))
        self.comboBox.setItemText(6, _translate("MainWindow", "7"))
        self.comboBox.setItemText(7, _translate("MainWindow", "8"))
        self.comboBox.setItemText(8, _translate("MainWindow", "9"))
        self.comboBox.setItemText(9, _translate("MainWindow", "10"))
        self.comboBox.setItemText(10, _translate("MainWindow", "11"))
        self.comboBox.setItemText(11, _translate("MainWindow", "12"))
        self.comboBox.setItemText(12, _translate("MainWindow", "13"))
        self.comboBox.setItemText(13, _translate("MainWindow", "14"))
        self.comboBox.setItemText(14, _translate("MainWindow", "15"))
        self.comboBox.setItemText(15, _translate("MainWindow", "16"))
        self.comboBox.setItemText(16, _translate("MainWindow", "17"))
        self.comboBox.setItemText(17, _translate("MainWindow", "18"))
        self.comboBox.setItemText(18, _translate("MainWindow", "19"))
        self.comboBox.setItemText(19, _translate("MainWindow", "20"))
        self.comboBox.setItemText(20, _translate("MainWindow", "21"))
        self.comboBox.setItemText(21, _translate("MainWindow", "22"))
        self.comboBox.setItemText(22, _translate("MainWindow", "23"))
        self.comboBox.setItemText(23, _translate("MainWindow", "24"))
        self.comboBox.setItemText(24, _translate("MainWindow", "25"))
        self.comboBox.setItemText(25, _translate("MainWindow", "26"))
        self.label_3.setText(_translate("MainWindow", "MaxCurrent"))
        self.label_5.setText(_translate("MainWindow", "GPIB addr"))
        self.label_12.setText(_translate("MainWindow", "LoadCH5"))
        self.label.setText(_translate("MainWindow", "LoadCH1"))
        self.label_11.setText(_translate("MainWindow", "LoadCH3"))
        self.label_2.setText(_translate("MainWindow", "Channel"))
        self.lineEdit_L3.setText(_translate("MainWindow", "80"))
        self.lineEdit_L1.setText(_translate("MainWindow", "80"))
        self.label_14.setText(_translate("MainWindow", "LoadCH9"))
        self.lineEdit_L5.setText(_translate("MainWindow", "80"))
        self.label_13.setText(_translate("MainWindow", "LoadCH7"))
        self.lineEdit_L7.setText(_translate("MainWindow", "80"))
        self.lineEdit_L9.setText(_translate("MainWindow", "80"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Eload2 Chroma 63312"))
        self.label_16.setText(_translate("MainWindow", "MaxCurrent"))
        self.lineEdit_L51.setText(_translate("MainWindow", "240"))
        self.label_9.setText(_translate("MainWindow", "Select "))
        self.label_10.setText(_translate("MainWindow", "GPIB addr"))
        self.comboBox_2.setCurrentText(_translate("MainWindow", "1"))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "1"))
        self.comboBox_2.setItemText(1, _translate("MainWindow", "2"))
        self.comboBox_2.setItemText(2, _translate("MainWindow", "3"))
        self.comboBox_2.setItemText(3, _translate("MainWindow", "4"))
        self.comboBox_2.setItemText(4, _translate("MainWindow", "5"))
        self.comboBox_2.setItemText(5, _translate("MainWindow", "6"))
        self.comboBox_2.setItemText(6, _translate("MainWindow", "7"))
        self.comboBox_2.setItemText(7, _translate("MainWindow", "8"))
        self.comboBox_2.setItemText(8, _translate("MainWindow", "9"))
        self.comboBox_2.setItemText(9, _translate("MainWindow", "10"))
        self.comboBox_2.setItemText(10, _translate("MainWindow", "11"))
        self.comboBox_2.setItemText(11, _translate("MainWindow", "12"))
        self.comboBox_2.setItemText(12, _translate("MainWindow", "13"))
        self.comboBox_2.setItemText(13, _translate("MainWindow", "14"))
        self.comboBox_2.setItemText(14, _translate("MainWindow", "15"))
        self.comboBox_2.setItemText(15, _translate("MainWindow", "16"))
        self.comboBox_2.setItemText(16, _translate("MainWindow", "17"))
        self.comboBox_2.setItemText(17, _translate("MainWindow", "18"))
        self.comboBox_2.setItemText(18, _translate("MainWindow", "19"))
        self.comboBox_2.setItemText(19, _translate("MainWindow", "20"))
        self.comboBox_2.setItemText(20, _translate("MainWindow", "21"))
        self.comboBox_2.setItemText(21, _translate("MainWindow", "22"))
        self.comboBox_2.setItemText(22, _translate("MainWindow", "23"))
        self.comboBox_2.setItemText(23, _translate("MainWindow", "24"))
        self.comboBox_2.setItemText(24, _translate("MainWindow", "25"))
        self.comboBox_2.setItemText(25, _translate("MainWindow", "26"))
        self.groupBox_3.setTitle(_translate("MainWindow", "DC Source Agilent"))
        self.pushButton_4.setText(_translate("MainWindow", "On"))
        self.pushButton_5.setText(_translate("MainWindow", "Off"))
        self.label_17.setText(_translate("MainWindow", "Vin"))
        self.lineEdit_5.setInputMask(_translate("MainWindow", "99.9"))
        self.lineEdit_5.setText(_translate("MainWindow", "12.0"))
        self.label_18.setText(_translate("MainWindow", "MaxCurrent"))
        self.lineEdit_6.setInputMask(_translate("MainWindow", "99"))
        self.lineEdit_6.setText(_translate("MainWindow", "60"))
        self.label_20.setText(_translate("MainWindow", "GPIB addr"))
        self.comboBox_3.setCurrentText(_translate("MainWindow", "1"))
        self.comboBox_3.setItemText(0, _translate("MainWindow", "1"))
        self.comboBox_3.setItemText(1, _translate("MainWindow", "2"))
        self.comboBox_3.setItemText(2, _translate("MainWindow", "3"))
        self.comboBox_3.setItemText(3, _translate("MainWindow", "4"))
        self.comboBox_3.setItemText(4, _translate("MainWindow", "5"))
        self.comboBox_3.setItemText(5, _translate("MainWindow", "6"))
        self.comboBox_3.setItemText(6, _translate("MainWindow", "7"))
        self.comboBox_3.setItemText(7, _translate("MainWindow", "8"))
        self.comboBox_3.setItemText(8, _translate("MainWindow", "9"))
        self.comboBox_3.setItemText(9, _translate("MainWindow", "10"))
        self.comboBox_3.setItemText(10, _translate("MainWindow", "11"))
        self.comboBox_3.setItemText(11, _translate("MainWindow", "12"))
        self.comboBox_3.setItemText(12, _translate("MainWindow", "13"))
        self.comboBox_3.setItemText(13, _translate("MainWindow", "14"))
        self.comboBox_3.setItemText(14, _translate("MainWindow", "15"))
        self.comboBox_3.setItemText(15, _translate("MainWindow", "16"))
        self.comboBox_3.setItemText(16, _translate("MainWindow", "17"))
        self.comboBox_3.setItemText(17, _translate("MainWindow", "18"))
        self.comboBox_3.setItemText(18, _translate("MainWindow", "19"))
        self.comboBox_3.setItemText(19, _translate("MainWindow", "20"))
        self.comboBox_3.setItemText(20, _translate("MainWindow", "21"))
        self.comboBox_3.setItemText(21, _translate("MainWindow", "22"))
        self.comboBox_3.setItemText(22, _translate("MainWindow", "23"))
        self.comboBox_3.setItemText(23, _translate("MainWindow", "24"))
        self.comboBox_3.setItemText(24, _translate("MainWindow", "25"))
        self.comboBox_3.setItemText(25, _translate("MainWindow", "26"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Input efficiency condition"))
        self.label_6.setText(_translate("MainWindow", "Imax"))
        self.lineEdit_2.setInputMask(_translate("MainWindow", "999"))
        self.lineEdit_2.setText(_translate("MainWindow", "600"))
        self.label_7.setText(_translate("MainWindow", "Istep"))
        self.lineEdit_3.setInputMask(_translate("MainWindow", "999"))
        self.lineEdit_3.setText(_translate("MainWindow", "5"))
        self.label_8.setText(_translate("MainWindow", "Delay"))
        self.lineEdit_4.setInputMask(_translate("MainWindow", "99"))
        self.lineEdit_4.setText(_translate("MainWindow", "2"))
        self.pushButton.setText(_translate("MainWindow", "Detect GPIB device"))
        self.pushButton_2.setText(_translate("MainWindow", "Open result"))
        self.groupBox_5.setTitle(_translate("MainWindow", "Option"))
        self.checkBox.setText(_translate("MainWindow", "onlive curve"))
        self.label_19.setText(_translate("MainWindow", "Save to:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
